# Generated by Django 3.2.16 on 2022-11-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='excerpt',
        ),
    ]
