# Generated by Django 3.2.16 on 2022-11-16 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_member_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='title',
            new_name='role',
        ),
    ]
