# Generated by Django 3.2.16 on 2022-11-21 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_title_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='blurb',
        ),
    ]
