# Generated by Django 3.2.16 on 2022-11-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_member_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_email',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
