# Generated by Django 3.2.16 on 2022-11-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_member_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(max_length=200),
        ),
    ]
